### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by giovannicaligaris** [flathub/org.telegram.desktop#18] opened 2017-12-17 11:17 UTC
Having an error when trying to install Telegram.

```
flatpak install flathub org.telegram.desktop
Required runtime for org.telegram.desktop/x86_64/stable (org.kde.Platform/x86_64/5.9) is not installed, searching...
Found in remote flathub, do you want to install it? [y/n]: y
Installing: org.kde.Platform/x86_64/5.9 from flathub
[####################] 12 delta parts, 40 loose fetched; 224510 KiB transfe
Installing: org.kde.Platform.Locale/x86_64/5.9 from flathub
[####################] 3 metadata, 1 content objects fetched; 13 KiB transf
Installing: org.telegram.desktop/x86_64/stable from flathub
[####################] 1 metadata, 0 content objects fetched; 569 B transfe
error: GDBus.Error:org.freedesktop.DBus.Error.Failed: Error deploying: Key file does not start with a group
```

**Comment by tingvarsson** [comment] 2017-12-17 18:44
I'm having the same issues:

```
[root@umaro ~]# flatpak install flathub org.telegram.desktop --verbose
F: Opening system flatpak installation at path /var/lib/flatpak
F: Fetching summary file for remote ‘flathub’
F: Updating dependent runtime runtime/org.kde.Platform/x86_64/5.9
F: Transaction: update flathub:runtime/org.kde.Platform/x86_64/5.9[$old]
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Transaction: install/update flathub:runtime/org.freedesktop.Platform.GL.nvidia-387-34/x86_64/1.4[*]
F: Transaction: install/update flathub:runtime/org.freedesktop.Platform.VAAPI.Intel/x86_64/1.6[*]
F: Transaction: install/update flathub:runtime/org.kde.Platform.Locale/x86_64/5.9[/en]
F: Transaction: install flathub:app/org.telegram.desktop/x86_64/stable[*]
F: Updating remote metadata for flathub
Installing: org.telegram.desktop/x86_64/stable from flathub
[####################] 1 metadata, 0 content objects fetched; 569 B transferred in 0 secondsF: No checksum specified, getting tip of app/org.telegram.desktop/x86_64/stable from origin flathub
F: tip resolved to: bfa7d1d019292460f742d2f747a4a69bb81c570a47f935f4e22c69c19fc87026

error: Key file does not start with a group
```

**Comment by grulja** [comment] 2017-12-19 08:53
Works for me. I guess there were some issues with the flathub server, can you try it again?

**Comment by giovannicaligaris** [comment] 2017-12-19 14:29
I am still having the same issue. I even ran flatpak update first.

$ flatpak install flathub org.telegram.desktop
Installing: org.telegram.desktop/x86_64/stable from flathub
[####################] 1 metadata, 0 content objects fetched; 569 B trans
error: GDBus.Error:org.freedesktop.DBus.Error.Failed: Error deploying: Key file does not start with a group

**Comment by alexlarsson** [comment] 2017-12-20 08:51
Can you try doing `rm -rf /var/tmp/flatpak-cache-*` first?

**Comment by alexlarsson** [comment] 2017-12-20 08:52
That should force it to re-download everything. Maybe something is broken in the partial download or something.

**Comment by giovannicaligaris** [comment] 2017-12-21 07:38
Same issue

```
$ rm -rf /var/tmp/flatpak-cache-*
$ flatpak install flathub org.telegram.desktop
Required runtime for org.telegram.desktop/x86_64/stable (org.kde.Platform/x86_64/5.9) is not installed, searching...
Found in remote flathub, do you want to install it? [y/n]: y
Installing: org.kde.Platform/x86_64/5.9 from flathub
[####################] 12 delta parts, 55 loose fetched; 236319 KiB transf
Installing: org.kde.Platform.Locale/x86_64/5.9 from flathub
[####################] 3 metadata, 1 content objects fetched; 13 KiB trans
Installing: org.telegram.desktop/x86_64/stable from flathub
[####################] 1 metadata, 0 content objects fetched; 569 B transf
error: GDBus.Error:org.freedesktop.DBus.Error.Failed: Error deploying: Key file does not start with a group
```

**Comment by alexlarsson** [comment] 2017-12-21 08:54
Does installing it per user work?
I.e:
```
flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak install --user flathub org.telegram.desktop
```

Also, what is the full output of: `flatpak install -v --ostree-verbose flathub org.telegram.desktop`

**Comment by giovannicaligaris** [comment] 2017-12-21 08:59
Similar issue again

```
$ flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
$ flatpak install --user flathub org.telegram.desktopInstalling for user: org.telegram.desktop/x86_64/stable from flathub
[####################] 1 delta parts, 2 loose fetched; 20631 KiB transferr
error: Key file does not start with a group
```

```
$ flatpak install -v --ostree-verbose flathub org.telegram.desktop
F: Opening system flatpak installation at path /var/lib/flatpak
F: Fetching summary file for remote ‘flathub’
F: Adding GPG keyring data from flathub.trustedkeys.gpg to verifier
F: Updating dependent runtime runtime/org.kde.Platform/x86_64/5.9
F: Transaction: update flathub:runtime/org.kde.Platform/x86_64/5.9[$old]
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Transaction: install/update flathub:runtime/org.freedesktop.Platform.VAAPI.Intel/x86_64/1.6[*]
F: Transaction: install/update flathub:runtime/org.kde.Platform.Locale/x86_64/5.9[/en]
F: Transaction: install flathub:app/org.telegram.desktop/x86_64/stable[*]
F: Updating remote metadata for flathub
Installing: org.telegram.desktop/x86_64/stable from flathub
F: Using new tmpdir staging-71073b58-696a-45b6-9395-937ad248e93f-ZXYOjd
F: Adding GPG keyring data from flathub.trustedkeys.gpg to verifier
F: starting fetch of bfa7d1d019292460f742d2f747a4a69bb81c570a47f935f4e22c69c19fc87026.commit (detached)
F: fetch of bfa7d1d019292460f742d2f747a4a69bb81c570a47f935f4e22c69c19fc87026.commit (detached) complete
F: Adding GPG keyring data from flathub.trustedkeys.gpg to verifier
F: pull: idle, exiting mainloop
F: Adding GPG keyring data from flathub.trustedkeys.gpg to verifier
F: starting fetch of bfa7d1d019292460f742d2f747a4a69bb81c570a47f935f4e22c69c19fc87026.commit (detached)
F: fetch of bfa7d1d019292460f742d2f747a4a69bb81c570a47f935f4e22c69c19fc87026.commit (detached) complete
F: Adding GPG keyring data from flathub.trustedkeys.gpg to verifier
F: pull: idle, exiting mainloop
F: txn commit staging-71073b58-696a-45b6-9395-937ad248e93f-ZXYOjd
[####################] 1 metadata, 0 content objects fetched; 569 B transfF: Calling system helper: Deploy

error: GDBus.Error:org.freedesktop.DBus.Error.Failed: Error deploying: Key file does not start with a group

```

**Comment by alexlarsson** [comment] 2017-12-21 09:20
Oh. Interesting. This is caused by the fact that the app id happens to end with ".desktop", so the newly exported binary-by-appid tries to export the binary as a desktop file..

**Comment by giovannicaligaris** [comment] 2017-12-21 10:06
Ah, that's makes sense. Should I try to re install it again?

**Comment by alexlarsson** [comment] 2017-12-21 11:23
No, wait for 0.10.2.1, it has a fix for this

**Closed by alexlarsson** 2017-12-21 11:23 UTC

**Comment by giovannicaligaris** [comment] 2017-12-21 16:25
Flatpak has just been updated. It works now!
