### ISSUE TITLE
New processes every time the app is brought to the foreground

### ISSUE THREAD

**Issue by bertogg** [flathub/org.telegram.desktop#287] opened 2021-07-22 22:48 UTC
How to reproduce:

- Open Telegram
- Close the window with Ctrl-W (the app is still running in the background)
- Bring it back to the foreground by typing the name on the GNOME shell launcher

The app is brought to the foreground (as expected) but these new processes appear and remain there even after the app shuts down completely:

```
26418 tty2     S+     0:00 bwrap --args 37 telegram-desktop --
26428 ?        Sl     0:00  \_ /app/bin/telegram-desktop -basegtkintegration :1.547 org.telegram.desktop.BaseGtkIntegration-4f43c8f460a56920b7f24fbaa55a0da0
26430 ?        Sl     0:00  \_ /app/bin/telegram-desktop -gtkintegration :1.547 org.telegram.desktop.GtkIntegration-4f43c8f460a56920b7f24fbaa55a0da0

```

Reproduced with Telegram `aa4a4a7408e8`  and `org.freedesktop.Platform/x86_64/20.08` commit `63c4b3103256`

**Comment by ilya-fedin** [comment] 2021-07-22 23:32
Attach to them with gdb and find where they hanged

**Comment by bertogg** [comment] 2021-07-26 09:36
So every time I run `telegram-desktop` and there's a running instance I get two of these:

```
   48 ?        Sl     0:00 /app/bin/telegram-desktop -basegtkintegration :1.390 org.telegram.desktop.BaseGtkIntegration-4f43c8f460a56920b7f24fbaa55a0da0
   50 ?        Sl     0:00 /app/bin/telegram-desktop -gtkintegration :1.390 org.telegram.desktop.GtkIntegration-4f43c8f460a56920b7f24fbaa55a0da0

```

Gdb shows exactly the same for both cases:

```
Thread 3 (Thread 0x7f16329ff700 (LWP 54)):
#0  0x00007f16374ff53f in poll () at /usr/lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f1639560a9e in g_main_context_iterate.constprop () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f1639560e23 in g_main_loop_run () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f16397bc50a in gdbus_shared_thread_func () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#4  0x00007f163958a861 in g_thread_proxy () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007f1639b384d2 in start_thread () at /usr/lib/x86_64-linux-gnu/libpthread.so.0
#6  0x00007f163750a323 in clone () at /usr/lib/x86_64-linux-gnu/libc.so.6

Thread 2 (Thread 0x7f16337ff700 (LWP 53)):
#0  0x00007f16374ff53f in poll () at /usr/lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f1639560a9e in g_main_context_iterate.constprop () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f1639560bd3 in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f1639560c21 in glib_worker_main () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007f163958a861 in g_thread_proxy () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007f1639b384d2 in start_thread () at /usr/lib/x86_64-linux-gnu/libpthread.so.0
#6  0x00007f163750a323 in clone () at /usr/lib/x86_64-linux-gnu/libc.so.6

Thread 1 (Thread 0x7f1634135100 (LWP 48)):
#0  0x00007f16374ff53f in poll () at /usr/lib/x86_64-linux-gnu/libc.so.6
#1  0x00007f1639560a9e in g_main_context_iterate.constprop () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f1639560bd3 in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f163977f58d in g_application_run () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#4  0x000055b4a38e1740 in  ()
#5  0x000055b4a34ba549 in  ()
#6  0x000055b4a210b045 in  ()
#7  0x00007f1637430062 in __libc_start_main () at /usr/lib/x86_64-linux-gnu/libc.so.6
#8  0x000055b4a2115f3e in  ()
```

**Comment by ilya-fedin** [comment] 2021-07-26 11:08
That's weird... If they're in poll, then they should close when parent process closes dbus connection...

**Comment by ilya-fedin** [comment] 2021-07-26 11:10
Personally I can't reproduce processes close with parent process for me

**Comment by ilya-fedin** [comment] 2021-07-31 13:34
Closing as this doesn't seem flatpak-specific

**Closed by ilya-fedin** 2021-07-31 13:34 UTC
