### ISSUE TITLE
Duplicated instances

### ISSUE THREAD

**Issue by anfrantic** [flathub/org.telegram.desktop#20] opened 2018-01-04 01:30 UTC
Spawns new instance every time been launched through the desktop launcher
![image](https://user-images.githubusercontent.com/5512677/34546868-91e9268e-f0ff-11e7-9ef2-95103b3031ff.png)

OS: Fedora 27x64
DE: GnomeShell/Wayland
Flatpak: 0.10.2.1

**Comment by Barthalion** [comment] 2018-01-10 00:50
It works fine here. What does `flatpak info org.telegram.desktop` show?

**Comment by anfrantic** [comment] 2018-01-10 04:41
Ref: app/org.telegram.desktop/x86_64/stable
ID: org.telegram.desktop
Arch: x86_64
Branch: stable
Origin: flathub
Date: 2017-11-15 10:44:46 +0000
Subject: Build org.telegram.desktop at 436d74338ca902f66ce4b1c9a239fc19f9d5d957
Commit: bfa7d1d019292460f742d2f747a4a69bb81c570a47f935f4e22c69c19fc87026
Parent: b0e638067e74f67e650f5b7338760b26afbc12a11127b3b05db95925c8c5a3c3
Location: /var/lib/flatpak/app/org.telegram.desktop/x86_64/stable/bfa7d1d019292460f742d2f747a4a69bb81c570a47f935f4e22c69c19fc87026
Installed size: 40.3 MB
Runtime: org.kde.Platform/x86_64/5.9

**Comment by aleixpol** [comment] 2018-01-15 19:41
Not working here either.

**Comment by plagasul** [comment] 2018-03-08 16:37
I am on linuxmint cinnamon rosa and every time I run the desktop file it opens a new instance of telegram. If I run cli:

`"flatpak run org.telegram.desktop`

...it opens a new instance each time aswell.

```
~ $ flatpak info org.telegram.desktop
Referencia: app/org.telegram.desktop/x86_64/stable
ID: org.telegram.desktop
Arquitectura: x86_64
Rama: stable
Origen: flathub
Commit: 68c77269cc033895a1d5c195bbacb87fc9ccec316eabf07b7da22445b3cc9500
Localización: /var/lib/flatpak/app/org.telegram.desktop/x86_64/stable/68c77269cc033895a1d5c195bbacb87fc9ccec316eabf07b7da22445b3cc9500
Tamaño de la instalación: 46,3 MB
Runtime: org.kde.Platform/x86_64/5.9
```
Wouldn't this be an already applied fix for this problem?:

https://github.com/flathub/org.telegram.desktop/blob/master/telegram-single-instance.patch

Thanks

**Comment by jurf** [comment] 2018-03-22 16:39
I can confirm, same problem here, looks like the patch isn’t really working.

**Comment by grulja** [comment] 2018-03-27 10:12
Will be fixed with the next update which is being build currently.

**Closed by grulja** 2018-03-27 10:12 UTC

**Comment by jurf** [comment] 2018-03-27 14:38
Thanks so much, this was really annoying.
