### ISSUE TITLE
Saving file dialog open to a wrong (unusual) location !

### ISSUE THREAD

**Issue by Nokia808** [flathub/org.telegram.desktop#229] opened 2021-01-23 20:38 UTC
Hi. Inspite frequent update of this flatpak package, this issue remain !

To reproduce it:
1) right-click on a received file within Telegram,
2) from right-click list select "Save as"
3) look for saving as dialog file !

Example - see attached screenshot. 

This issue was found in many flatpak packages, but all of them that I know (like PDF Mix Tool) fix it ......
![1](https://user-images.githubusercontent.com/25375330/105613528-fde6e580-5dba-11eb-8801-12c6ee0f1c8d.png)

**Comment by gasinvein** [comment] 2021-01-23 20:42
As far as I understand, this may be fixed by flatpak/xdg-desktop-portal#552

**Comment by ilya-fedin** [comment] 2021-01-23 20:45
> This issue was found in many flatpak packages, but all of them that I know (like PDF Mix Tool) fix it ......

How to fix it?

**Comment by ilya-fedin** [comment] 2021-01-23 20:48
> As far as I understand, this may be fixed by [flatpak/xdg-desktop-portal#552](https://github.com/flatpak/xdg-desktop-portal/pull/552)

This is a SaveFile dialog, not an OpenDirectory dialog...

**Comment by gasinvein** [comment] 2021-01-23 20:51
Doesn't the save file dialog call open directory on startup to show the last used directory?

**Comment by ilya-fedin** [comment] 2021-01-23 20:56
This is about OpenDirectory method on OpenURI portal. It is unrelated to FileChooser portal.
https://github.com/flatpak/xdg-desktop-portal/issues/363#issuecomment-716347795

**Comment by Nokia808** [comment] 2021-01-24 11:56
Hi all ! 

As examples of how they fix this on other flatpak applications, see the following:

https://github.com/junrrein/pdfslicer/issues/72

&

https://gitlab.com/scarpetta/pdfmixtool/-/issues/13

Kindly, notice that I'm not programmer .......

**Comment by ilya-fedin** [comment] 2021-01-24 15:34
Looks like they just disabled the saving path feature and always opening the dialog with the default path. It's unliekly to be a way for tdesktop, so we can only wait when this will be fixed on portal side.

**Comment by ilya-fedin** [comment] 2021-02-17 18:58
Can't reproduce with 2.5.9

**Closed by ilya-fedin** 2021-02-17 18:58 UTC
