### ISSUE TITLE
The tray menu does not use system fonts

### ISSUE THREAD

**Issue by crbelaus** [flathub/org.telegram.desktop#66] opened 2019-02-16 14:48 UTC
When using right-click in the tray icon, the menu opens but uses a strange monospaced font instead of the one that is being used in the rest of the system. It can be seen in the following screenshot:

![telegram-tray-menu](https://user-images.githubusercontent.com/2965623/52901278-e0d62f00-3201-11e9-9649-ee0130d00455.png)

I am using Linux Mint 19.1 and Telegram Flatpak installed from FlatHub:

```
Ref: app/org.telegram.desktop/x86_64/stable
ID: org.telegram.desktop
Arch: x86_64
Branch: stable
Origin: flathub
Collection ID: org.flathub.Stable
Date: 2019-02-13 11:13:51 +0000
Subject: Update to 1.5.15 (8b779377)
Commit: 2e60a5ce3ecd5bf8c4551c1b5b3df37e7c55ad2ed0c977c1cf6ed14baa4075c4
Parent: 56b25db7758a79db449498d3cdd631fc2c30ed71a7e52c9180061cc92c642e65
Location: /var/lib/flatpak/app/org.telegram.desktop/x86_64/stable/2e60a5ce3ecd5bf8c4551c1b5b3df37e7c55ad2ed0c977c1cf6ed14baa4075c4
Installed size: 61,3 MB
Runtime: org.kde.Platform/x86_64/5.12
Sdk: org.kde.Sdk/x86_64/5.12
```

**Comment by jurf** [comment] 2019-02-17 12:49
Looks like #49.

**Comment by TingPing** [comment] 2019-02-18 13:53
Duplicate of #49

**Closed by TingPing** 2019-02-18 13:53 UTC

**Comment by Ravenow** [comment] 2019-03-06 09:03
Tray menu fonts still broken. I just installed telegram(1.5.15) and font still weird as on screenshot

**Comment by spectrum70** [comment] 2019-07-13 13:03
Same with 1.7.13
