### ISSUE TITLE
Choose file dialog opens in background

### ISSUE THREAD

**Issue by orschiro** [flathub/org.telegram.desktop#26] opened 2018-01-29 07:52 UTC
When wanting to upload a file, the choose file dialog opens in background instead of foreground.

Tested with Telegram Desktop 1.2.6 Flatpak on Fedora 27.

Anyone else with this?

Adding a screencast below:

https://youtu.be/YnKiOCRHkOU

**Comment by ahayzen** [comment] 2018-02-11 13:53
This also happens on Ubuntu 17.10 Wayland, I need to test under X as well as some other windows don't seem to auto raise under wayland.

But is very irritating, as if you have telegram maximised, you can't see the file choose popup behind, and then you think that the telegram app has frozen as you can't interact with it due to the "modal" dialog.

**Comment by TingPing** [comment] 2018-02-12 06:32
I've experienced this under X too, maybe related to how Qt uses the portals.

**Comment by grulja** [comment] 2018-03-27 06:06
In telegram portals are not involved because it uses some custom Gtk file dialog and not standard Qt file dialog which would automatically use portals.

**Comment by grulja** [comment] 2019-01-18 13:36
Should be fixed with https://github.com/flathub/org.telegram.desktop/commit/f9041d1f765fa03f048a0f9cb38d052130468bb7.

**Comment by orschiro** [comment] 2019-01-18 14:45
Thanks Jan! That's great.

**Comment by lungelimb** [comment] 2019-03-28 18:50
I think I have exact same issue under `swaywm`:
```
flatpak 1.2.4_1
xdg-desktop-portal-1.2.0_1
xdg-desktop-portal-gtk-1.2.0_1

latest org.telegram.desktop (updated just now with no luck)
```

Verbose output (Wayland):
```
Using Wayland-EGL
AL lib: (EE) ALCcaptureOSS_open: Could not open /dev/dsp: No such file or directory
Using the 'xdg-shell' shell integration
```

Actual behavior:
Window appears to be frozen and unfocused, no input response, no dialog window.
Tried under XWayland and "native" Wayland via `QT_QPA_PLATFORM=wayland-egl QT_WAYLAND_DISABLE_WINDOWDECORATION="1"` (from archwiki)

Slightly unrelated to this particular issue, but to app + swaywm:
The only difference in behavior between XWayland\Wayland is that notification pop-up under "native" Wayland backend does not act like 'float' window: every notification splits current workspace. I could put a rule in swaywm config like 'for window class="telegram-notification" float` to get around it, but I don't know its class or name (since there's no 'xdotool' in Wayland).
However, in XWayland notifications are perfectly fine -- they "float" like they should.

PS. I'm not sure if this is related, but when I open-up context menu in text-area (right mouse click) there is some verbose output:
```
qt.qpa.wayland: Non-toplevel surfaces can't request window states
qt.qpa.wayland: Wayland does not support QWindow:RequestActivate()
```

Thx in advance.

**Comment by ilya-fedin** [comment] 2020-08-30 11:40
Is this still an issue?

**Comment by im-n1** [comment] 2020-09-25 06:21
My file-chooser doesnt open at all.

**Comment by ilya-fedin** [comment] 2020-09-25 07:32
> My file-chooser doesnt open at all.

what is your portal backend?

**Comment by im-n1** [comment] 2020-09-25 09:20
> > My file-chooser doesnt open at all.
> 
> what is your portal backend?

I'm sorry I have no idea what are you asking to?

**Comment by ilya-fedin** [comment] 2020-09-25 09:51
> I'm sorry I have no idea what are you asking to?

You should have xdg-desktop-portal-kde or xdg-desktop-portal-gtk in order to have dialogs in flatpak applications

**Comment by im-n1** [comment] 2020-09-25 11:34
I just did install gtk version but no difference.

**Comment by ilya-fedin** [comment] 2020-09-25 11:48
> I just did install gtk version but no difference.

Did you restart your computer?

**Comment by im-n1** [comment] 2020-09-25 11:54
Just the telegram. On Uninx you don't really have to restart your machine. What service needs to be reloaded?

**Comment by ilya-fedin** [comment] 2020-09-25 11:55
>  What service needs to be reloaded?

I don't know

**Comment by gasinvein** [comment] 2020-09-25 12:08
You don't need full reboot to make dbus pick up new services. Just a relogin is enough, or even `systemctl --user reload dbus`.

**Comment by im-n1** [comment] 2020-09-26 08:02
I can confirm that reloading worked. INstalling desktop portal solved the problem.

**Comment by ilya-fedin** [comment] 2021-02-08 04:38
> Is this still an issue?

no one answered, I assume it is not

**Closed by ilya-fedin** 2021-02-08 04:38 UTC

**Comment by shoeper** [comment] 2021-04-22 11:39
On Fedora 33 this is still an issue.
