### ISSUE TITLE
Telegram freezes when trying to upload an attachment (version2.8.4)

### ISSUE THREAD

**Issue by hsmroot** [flathub/org.telegram.desktop#277] opened 2021-07-03 21:23 UTC
This issue just started today. So as the title goes, when I try to make an attachment, be it to saved messages or to any chat, the whole UI of Telegram freezes and then I get the force quit/wait option displayed to me.

I know this flatpak, but if it helps, I'm using Fedora Silverblue 34

**Comment by gasinvein** [comment] 2021-07-03 21:24
Duplicate of #276

**Closed by gasinvein** 2021-07-03 21:24 UTC
