### ISSUE TITLE
Formatting of hyperlinks is broken

### ISSUE THREAD

**Issue by avimmer** [flathub/org.telegram.desktop#95] opened 2019-09-20 15:17 UTC
![Screenshot from 2019-09-20 18-11-10](https://user-images.githubusercontent.com/10907842/65338248-74c20c00-dbd2-11e9-800c-2af742a7fb05.png)
```
Telegram Desktop - Telegram Desktop messenger

           ID: org.telegram.desktop
          Ref: app/org.telegram.desktop/x86_64/stable
         Arch: x86_64
       Branch: stable
      Version: 1.8.8
      License: GPL-3.0
       Origin: flathub
   Collection: org.flathub.Stable
 Installation: system
    Installed: 68.4 MB
      Runtime: org.kde.Platform/x86_64/5.12
          Sdk: org.kde.Sdk/x86_64/5.12

Active commit: 078e3bd4760b5059ce9797e8f5a70232ed494e830ed947c0111cb9cdb05d1100
Latest commit: dfa291688c385f8b4aed73ffd16b1e4f9f513f33b870de705d8e85420357f047
       Parent: a390cda305631657d430172418aa1aa9d7d138f0e66adc51f606b17fe6436a0c
      Subject: Include QStandardPaths header to fix the build (183c7b85)
         Date: 2019-09-13 19:09:13 +0000
```

Please tell if more information is needed,
Thank you

**Comment by NotAFile** [comment] 2019-09-22 16:27
according to https://github.com/telegramdesktop/tdesktop/issues/6584, this is due to a mismatch of the Qt version used.

**Comment by grulja** [comment] 2019-09-23 05:52
Duplicate of https://github.com/flathub/org.telegram.desktop/issues/92. Should be fixed already.

**Closed by grulja** 2019-09-23 05:52 UTC

**Comment by AsciiWolf** [comment] 2019-11-08 14:00
This issue just reappeared after latest KDE runtime update.
