### ISSUE TITLE
telegram-desktop crash in Wayland GNOME session

### ISSUE THREAD

**Issue by develop7** [flathub/org.telegram.desktop#193] opened 2020-09-16 09:46 UTC
Repro:

1. Run `flatpak run org.telegram.desktop` in Wayland GNOME session

Expected: it runs successfully

Instead: it crashes producing following console output

<details>
<summary>Output</summary>

```
$ flatpak run org.telegram.desktop
(process:2): Telegram-WARNING **: 12:41:03.912: Unfortunately, GTK integration conflicts with qgtk2 platformtheme and style. Therefore, QT_QPA_PLATFORMTHEME and QT_STYLE_OVERRIDE will be unset.
Telegram-Message: 12:41:03.914: This can be ignored by setting TDESKTOP_I_KNOW_ABOUT_GTK_INCOMPATIBILITY environment variable to any value, however, if qgtk2 theme or style is used, this will lead to a crash.
Telegram-Message: 12:41:03.914: GTK integration can be disabled by setting TDESKTOP_DISABLE_GTK_INTEGRATION to any value. Keep in mind that this will lead to clipboard issues and tdesktop will be unable to get settings from GTK (such as decoration layout, dark mode & more).
Qt: Session management error: None of the authentication protocols specified are supported

(process:2): Gtk-WARNING **: 12:41:04.149: Locale not supported by C library.
	Using the fallback 'C' locale.
Gtk-Message: 12:41:04.225: Failed to load module "canberra-gtk-module"
Gtk-Message: 12:41:04.225: Failed to load module "canberra-gtk-module"
Telegram-Message: 12:41:04.229: You can disable tray icon counter with TDESKTOP_DISABLE_TRAY_COUNTER and make it look better if it is monochrome.
error: : cannot open
error: : cannot open
error: : cannot open
qt.qpa.xcb: xcb_shm_create_segment() failed for size 4755348
The X11 connection broke (error 2). Did the X11 server die?
```

</details>

Workaround: run `flatpak override --env=QT_QPA_PLATFORM=wayland org.telegram.desktop` (add `--user` if needed).

**Comment by ilya-fedin** [comment] 2020-09-16 16:08
Duplicate of #191

**Closed by ilya-fedin** 2020-09-16 16:08 UTC
