### ISSUE TITLE
Choose file dialog opens in background

### ISSUE THREAD

**Issue by Esokrates** [flathub/org.telegram.desktop#110] opened 2019-10-30 22:36 UTC
This happens to me in gnome-shell: When attaching a file, the file chooser appears behind the telegram window (is not focused) and I get a notification that the file chooser portal is ready.
This is really annoying behavior, don't know if this is directly related to telegram, but I do not observe the issue with other apps.

**Comment by grulja** [comment] 2019-10-31 09:48
Duplicate of https://github.com/flathub/org.telegram.desktop/issues/110.

**Closed by grulja** 2019-10-31 09:48 UTC
