### ISSUE TITLE
Crash on Manjaro Gnome Wayland session

### ISSUE THREAD

**Issue by teohhanhui** [flathub/org.telegram.desktop#194] opened 2020-09-24 11:30 UTC
```
~ >>> flatpak run org.telegram.desktop                                      [1]

(process:2): Telegram-WARNING **: 19:27:56.273: Unfortunately, GTK integration conflicts with qgtk2 platformtheme and style. Therefore, QT_QPA_PLATFORMTHEME and QT_STYLE_OVERRIDE will be unset.
Telegram-Message: 19:27:56.276: This can be ignored by setting TDESKTOP_I_KNOW_ABOUT_GTK_INCOMPATIBILITY environment variable to any value, however, if qgtk2 theme or style is used, this will lead to a crash.
Telegram-Message: 19:27:56.276: GTK integration can be disabled by setting TDESKTOP_DISABLE_GTK_INTEGRATION to any value. Keep in mind that this will lead to clipboard issues and tdesktop will be unable to get settings from GTK (such as decoration layout, dark mode & more).
Qt: Session management error: None of the authentication protocols specified are supported
Gtk-Message: 19:27:56.397: Failed to load module "canberra-gtk-module"
Gtk-Message: 19:27:56.397: Failed to load module "canberra-gtk-module"
Telegram-Message: 19:27:56.400: You can disable tray icon counter with TDESKTOP_DISABLE_TRAY_COUNTER and make it look better if it is monochrome.
error: : cannot open
error: : cannot open
error: : cannot open
The X11 connection broke (error 2). Did the X11 server die?
```

**Comment by ilya-fedin** [comment] 2020-09-24 11:31
Another duplicate of #191

**Closed by ilya-fedin** 2020-09-24 11:31 UTC

**Comment by gasinvein** [comment] 2020-09-24 11:33
I wonder if we should stop forcing xcb on Gnome. Looks like native wayland works better now.
