### ISSUE TITLE
SELinux Alert on Fedora 34

### ISSUE THREAD

**Issue by samuelsmal** [flathub/org.telegram.desktop#262] opened 2021-05-04 09:58 UTC
Not the same as #260.

Here are the details from my SELinux Alert Browser:

```
SELinux is preventing gnome-shell from read access on the lnk_file /var/lib/flatpak/exports/share/applications/org.telegram.desktop.desktop.

*****  Plugin catchall_labels (83.8 confidence) suggests   *******************

If you want to allow gnome-shell to have read access on the org.telegram.desktop.desktop lnk_file
Then you need to change the label on /var/lib/flatpak/exports/share/applications/org.telegram.desktop.desktop
Do
# semanage fcontext -a -t FILE_TYPE '/var/lib/flatpak/exports/share/applications/org.telegram.desktop.desktop'
where FILE_TYPE is one of the following: NetworkManager_etc_rw_t, NetworkManager_etc_t, abrt_etc_t, abrt_var_cache_t, admin_home_t, aiccu_etc_t, alsa_etc_rw_t, antivirus_conf_t, asterisk_etc_t, bin_t, bitlbee_conf_t, bluetooth_conf_t, boot_t, bootloader_etc_t, cache_home_t, cert_t, cgconfig_etc_t, cgroup_t, cgrules_etc_t, cluster_conf_t, cobbler_etc_t, condor_conf_t, config_home_t, config_usr_t, conntrackd_conf_t, container_config_t, couchdb_conf_t, courier_etc_t, cpucontrol_conf_t, cupsd_etc_t, cupsd_rw_etc_t, data_home_t, dbus_home_t, dbusd_etc_t, ddclient_etc_t, device_t, devlog_t, dhcp_etc_t, dictd_etc_t, dnsmasq_etc_t, dovecot_etc_t, ecryptfs_t, etc_mail_t, etc_runtime_t, etc_t, exports_t, fetchmail_etc_t, file_context_t, fingerd_etc_t, firewalld_etc_rw_t, firstboot_etc_t, fonts_cache_t, fonts_t, ftpd_etc_t, gconf_etc_t, gconf_home_t, gdomap_conf_t, getty_etc_t, gkeyringd_gnome_home_t, gkeyringd_tmp_t, gnome_home_t, gpm_conf_t, gstreamer_home_t, hddtemp_etc_t, home_root_t, hostname_etc_t, httpd_config_t, hwdata_t, ibacm_conf_t, icc_data_home_t, innd_etc_t, irc_conf_t, irssi_etc_t, kdump_etc_t, kmscon_conf_t, krb5_conf_t, krb5kdc_conf_t, l2tp_conf_t, ld_so_t, lib_t, likewise_etc_t, lircd_etc_t, locale_t, lvm_etc_t, machineid_t, man_cache_t, man_t, mcelog_etc_t, mdadm_conf_t, minidlna_conf_t, minissdpd_conf_t, mock_etc_t, modules_conf_t, mozilla_conf_t, mozilla_plugin_tmp_t, mozilla_plugin_tmpfs_t, mpd_etc_t, mplayer_etc_t, mrtg_etc_t, mscan_etc_t, munin_etc_t, mysqld_etc_t, nagios_etc_t, named_conf_t, net_conf_t, nrpe_etc_t, nslcd_conf_t, ntop_etc_t, ntp_conf_t, nut_conf_t, opendnssec_conf_t, openvpn_etc_rw_t, openvpn_etc_t, openvswitch_rw_t, oracleasm_conf_t, pads_config_t, pam_var_console_t, pdns_conf_t, pegasus_conf_t, pingd_etc_t, piranha_etc_rw_t, piranha_web_conf_t, polipo_etc_t, portreserve_etc_t, postfix_etc_t, postfix_postdrop_t, postgresql_etc_t, postgrey_etc_t, pppd_etc_t, prelude_correlator_config_t, printconf_t, proc_t, psad_etc_t, ptal_etc_t, puppet_etc_t, qmail_etc_t, rabbitmq_conf_t, radiusd_etc_t, radvd_etc_t, redis_conf_t, rhnsd_conf_t, rhsmcertd_config_t, root_t, rpm_script_tmp_t, rpm_var_cache_t, rpm_var_lib_t, rsync_etc_t, samba_etc_t, sanlock_conf_t, security_t, selinux_config_t, selinux_login_config_t, shell_exec_t, shorewall_etc_t, slapd_etc_t, snapperd_conf_t, snappy_config_t, snort_etc_t, soundd_etc_t, spamd_etc_t, squid_conf_t, src_t, ssh_home_t, sslh_config_t, sssd_conf_t, sssd_var_lib_t, stunnel_etc_t, svc_conf_t, sysfs_t, syslog_conf_t, system_conf_t, system_db_t, system_dbusd_var_lib_t, systemd_hwdb_etc_t, systemd_userdbd_runtime_t, textrel_shlib_t, tftpd_etc_t, tmp_t, tor_etc_t, tuned_etc_t, tuned_rw_etc_t, udev_etc_t, udev_var_run_t, ulogd_etc_t, user_home_dir_t, user_home_t, user_tmp_t, userhelper_conf_t, usr_t, var_lock_t, var_run_t, var_t, varnishd_etc_t, virt_etc_t, virt_var_lib_t, virtlogd_etc_t, vmware_sys_conf_t, webalizer_etc_t, xdm_etc_t, xdm_log_t, xdm_rw_etc_t, xdm_tmpfs_t, xdm_var_lib_t, xdm_var_run_t, xserver_etc_t, xserver_log_t, ypserv_conf_t, zarafa_etc_t, zebra_conf_t.
Then execute:
restorecon -v '/var/lib/flatpak/exports/share/applications/org.telegram.desktop.desktop'


*****  Plugin catchall (17.1 confidence) suggests   **************************

If you believe that gnome-shell should be allowed read access on the org.telegram.desktop.desktop lnk_file by default.
Then you should report this as a bug.
You can generate a local policy module to allow this access.
Do
allow this access for now by executing:
# ausearch -c 'gnome-shell' --raw | audit2allow -M my-gnomeshell
# semodule -X 300 -i my-gnomeshell.pp

Additional Information:
Source Context                system_u:system_r:xdm_t:s0-s0:c0.c1023
Target Context                system_u:object_r:var_lib_t:s0
Target Objects                /var/lib/flatpak/exports/share/applications/org.te
                              legram.desktop.desktop [ lnk_file ]
Source                        gnome-shell
Source Path                   gnome-shell
Port                          <Unknown>
Host                          tir
Source RPM Packages           
Target RPM Packages           
SELinux Policy RPM            selinux-policy-targeted-3.14.6-36.fc33.noarch
Local Policy RPM              selinux-policy-targeted-3.14.6-36.fc33.noarch
Selinux Enabled               True
Policy Type                   targeted
Enforcing Mode                Enforcing
Host Name                     tir
Platform                      Linux tir 5.11.13-200.fc33.x86_64 #1 SMP Sun Apr
                              11 02:08:26 UTC 2021 x86_64 x86_64
Alert Count                   96
First Seen                    2021-04-01 21:33:19 CEST
Last Seen                     2021-04-18 17:19:31 CEST
Local ID                      7d5524c2-ead6-4261-a2c4-8e029b981fef

Raw Audit Messages
type=AVC msg=audit(1618759171.498:871): avc:  denied  { read } for  pid=20762 comm="gnome-shell" name="org.telegram.desktop.desktop" dev="dm-0" ino=2754647 scontext=system_u:system_r:xdm_t:s0-s0:c0.c1023 tcontext=system_u:object_r:var_lib_t:s0 tclass=lnk_file permissive=0


Hash: gnome-shell,xdm_t,var_lib_t,lnk_file,read
```

**Comment by ilya-fedin** [comment] 2021-05-04 10:00
What should we do to fix that?

**Comment by samuelsmal** [comment] 2021-05-04 10:02
no clue. but I thought this would be the right place for it. please correct me, or point me towards the right place if you think this is wrong.

**Comment by ilya-fedin** [comment] 2021-05-04 10:02
Unfortunately, I have no idea what to do with it :(

**Comment by gasinvein** [comment] 2021-05-04 10:09
@samuelsmal It's not the right place. Individual flatpak apps don't interact with selinux policy anyhow. Try searching Fedora's bugzilla for `selinux-policy` bugs mentioning flatpak, probably something similar was already reported.

**Comment by hfiguiere** [comment] 2021-05-04 21:23
I think it is this bug https://bugzilla.redhat.com/show_bug.cgi?id=1916652

Or something related.

**Comment by samuelsmal** [comment] 2021-05-05 15:15
Nice find, they fixed it with a [quickfix[(https://github.com/flatpak/flatpak/issues/4128#issuecomment-818019245)

**Comment by ilya-fedin** [comment] 2021-05-05 15:40
If they fixed that 23 days ago how you got that error then? :thinking:

**Comment by samuelsmal** [comment] 2021-05-05 16:28
hmm... I am using the version that were mentioned. so... I guess that didn't fix it?

**Comment by ilya-fedin** [comment] 2021-05-05 16:38
I don't see any fix by the link, I see that they only bisected to the cause, but still discussing how to fix it.

**Comment by ilya-fedin** [comment] 2021-06-17 18:01
Can we close the issue?

**Comment by gasinvein** [comment] 2021-06-17 18:08
I guess, we can't do anything about it in the scope of this app anyway.

**Comment by samuelsmal** [comment] 2021-06-18 09:06
I am still getting a ton of alerts. But I can use the app again. So... I guess this is a win?

**Closed** 2021-06-18 09:05 UTC
