### ISSUE TITLE
Dead keys do not appear to work

### ISSUE THREAD

**Issue by NotAFile** [flathub/org.telegram.desktop#11] opened 2017-11-06 10:43 UTC
This is very weird behavior I have only encountered in Telegram in flatpak. Dead keys like \` and `^` just produce no output at all.

```
Ref: app/org.telegram.desktop/x86_64/stable
ID: org.telegram.desktop
Arch: x86_64
Branch: stable
Origin: flathub
Commit: b0e638067e74f67e650f5b7338760b26afbc12a11127b3b05db95925c8c5a3c3
Location: /var/lib/flatpak/app/org.telegram.desktop/x86_64/stable/b0e638067e74f67e650f5b7338760b26afbc12a11127b3b05db95925c8c5a3c3
Installed size: 40.3 MB
Runtime: org.kde.Platform/x86_64/5.9
```

**Comment by alexlarsson** [comment] 2017-11-16 10:19
This works for me, i wonder what the difference is. Are you on X11 or Wayland?

**Comment by alexlarsson** [comment] 2017-11-16 10:22
And in general, what flatpak version and distro version are you on?

**Comment by NotAFile** [comment] 2017-11-16 11:18
I have by now isolated this issue to Wayland (or rather xwayland) only. Distro is fedora.

**Comment by alexlarsson** [comment] 2017-11-16 16:17
I wonder if it Qt + wayland interactions.

**Comment by jurf** [comment] 2018-03-22 16:41
Still an issue?

**Comment by tstdin** [comment] 2018-05-20 09:07
On Fedora 28, Wayland, Telegram in Flatpak version 1.2.17: the mentioned keys work fine.

But I have problems with czech diacritics - `ď`, `ň`, `ť`. These symbols need to be written in two steps - first the modifier `ˇ` that produces no output and then type the normal symbol; e.g. `ˇ` + `d` => `ď`.

Only the `ˇ` modifier is broken, the other one `´` works fine (e.g. `´` + `o` produces correctly `ó`.

**Comment by jurf** [comment] 2018-05-20 17:38
It works fine on my end – I even found out I can `ˇ` a number and get a subscript version: `2+1=3 ₂₊₁₌₃` 😀. I have the exact same environment as you.

**Comment by heftig** [comment] 2018-08-09 11:36
I'm trying to use Compose (Arch Linux, GNOME 3.28, X11, US layout, no IME, `compose:menu`).

I can enter `ö` (Compose `o` `"`) but not `€` (Compose `e` `=`). Pasting a `€` from the clipboard works.

**Comment by Fidelix** [comment] 2018-08-29 08:45
I'm using X and I have this problem with Skype.

**Comment by tstdin** [comment] 2019-01-10 10:05
> On Fedora 28, Wayland, Telegram in Flatpak version 1.2.17: the mentioned keys work fine.
> 
> But I have problems with czech diacritics - `ď`, `ň`, `ť`. These symbols need to be written in two steps - first the modifier `ˇ` that produces no output and then type the normal symbol; e.g. `ˇ` + `d` => `ď`.
> 
> Only the `ˇ` modifier is broken, the other one `´` works fine (e.g. `´` + `o` produces correctly `ó`.

Clean installation fixed the problem for me. First I tried reinstallation without cleaning the $HOME/.var/app/org.telegram.desktop, but the problem remained. But this worked

```
(sudo) flatpak remove org.telegram.desktop
rm -rf $HOME/.var/app/org.telegram.desktop
(sudo) flatpak install flathub org.telegram.desktop
```

What about cleaning everything (including this directory) in the cleanup stage?

**Comment by grulja** [comment] 2019-01-18 13:49
Is this issue still reproducible?

**Comment by heftig** [comment] 2019-01-18 13:51
Compose seems to work properly now; thanks.

**Comment by grulja** [comment] 2019-01-18 16:21
Closing for now. Please re-open if this is still reproducible.

**Comment by Mikaela** [comment] 2019-04-18 08:03
I think this is flatpak/flatpak#2031.

**Closed** 2019-04-18 08:22 UTC
