### ISSUE TITLE
Ubuntu 20.10: "bwrap: Can't bind mount ...files on ... i386-linux-gnu

### ISSUE THREAD

**Issue by mitchhentges** [flathub/org.telegram.desktop#246] opened 2021-03-17 15:02 UTC
```
$ flatpak info org.telegram.desktop                         

Telegram Desktop - Telegram Desktop messenger

          ID: org.telegram.desktop
         Ref: app/org.telegram.desktop/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 2.6.1
     License: GPL-3.0
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 67.3 MB
     Runtime: org.kde.Platform/x86_64/5.15
         Sdk: org.kde.Sdk/x86_64/5.15

      Commit: 2cb02b4037d74e2e8d6a8e5af6931a0dd56d31cff2d28b42d894332ecefe2138
      Parent: 2fa46b503435b6f97f5045cd4919a2c6e4ba952cfe3b5cb1ccc20ae8483ed63e
     Subject: Update tdesktop.git to 2.6.1 (a00067ef)
        Date: 2021-02-24 21:48:02 +0000
$ flatpak run org.telegram.desktop 
bwrap: Can't bind mount /oldroot/var/lib/flatpak/runtime/org.freedesktop.Sdk.Compat.i386/x86_64/20.08/a1f0728770a18427fc0f5cb2ee5cf89c16b55802943c6d85579439bdadae0c98/files on /newroot/usr/lib/i386-linux-gnu: No such file or directory
error: ldconfig failed, exit status 256
```

I'm fully up-to-date (March 17, 2021) on `apt` packages, `flatpak` packages, have rebooted since fully updating.
Let me know what other information I can provide, it's unclear what direction to poke next.
Thanks for publishing this flatpak! :beers:

**Comment by gasinvein** [comment] 2021-03-17 15:04
Duplicate of #243

**Closed by gasinvein** 2021-03-17 15:04 UTC
