### ISSUE TITLE
crash when set group picture

### ISSUE THREAD

**Issue by scafroglia93** [flathub/org.telegram.desktop#59] opened 2019-01-19 15:05 UTC
Reproduce

set profile picture inside group

**Comment by grulja** [comment] 2019-01-19 16:13
Sounds like duplicate of https://github.com/flathub/org.telegram.desktop/issues/54.

**Comment by grulja** [comment] 2019-01-21 06:56
Closing as duplicate of https://github.com/flathub/org.telegram.desktop/issues/54.

**Closed by grulja** 2019-01-21 06:56 UTC
