### ISSUE TITLE
Error attempting to run flatpak application: bwarp can't bind mount No such file or directory

### ISSUE THREAD

**Issue by Mek101** [flathub/org.telegram.desktop#243] opened 2021-03-16 13:35 UTC
There seems to be some kind of mounting issue: https://github.com/flatpak/flatpak/issues/4175

***

## Linux distribution and version
Linux Mint 20.1
## Flatpak version
Flatpak 1.10.2
## Description of the problem
Attempting to run telegram fails with:
```
mek101@mint-desktop:~$ flatpak run org.telegram.desktop 
bwrap: Can't bind mount /oldroot/var/lib/flatpak/runtime/org.freedesktop.Sdk.Compat.i386/x86_64/20.08/a1f0728770a18427fc0f5cb2ee5cf89c16b55802943c6d85579439bdadae0c98/files on /newroot/usr/lib/i386-linux-gnu: No such file or directory
error: ldconfig failed, exit status 256
```

Despite the directory being present: 
```
mek101@mint-desktop:~$ ls /var/lib/flatpak/runtime/org.freedesktop.Sdk.Compat.i386/x86_64/20.08/a1f0728770a18427fc0f5cb2ee5cf89c16b55802943c6d85579439bdadae0c98/
deploy  files  metadata
```
## Steps to reproduce
Install and run `org.telegram.desktop`

***

I also tried re-installing both telegram and the runtime, but with no avail.
I can't even try to explore the mounted chroot space since it fails:
```
mek101@mint-desktop:~$ flatpak run org.telegram.desktop --devel --command=bash 
bwrap: Can't bind mount /oldroot/var/lib/flatpak/runtime/org.freedesktop.Sdk.Compat.i386/x86_64/20.08/a1f0728770a18427fc0f5cb2ee5cf89c16b55802943c6d85579439bdadae0c98/files on /newroot/usr/lib/i386-linux-gnu: No such file or directory
error: ldconfig failed, exit status 256
```

**Comment by gasinvein** [comment] 2021-03-16 13:38
KDE runtime was broken in attempts to add multilib builds support, see https://invent.kde.org/packaging/flatpak-kde-runtime/-/issues/15
As a workaround you can uninstall `org.freedesktop.Sdk.Compat.i386`

**Comment by Mek101** [comment] 2021-03-16 13:39
Thanks!

**Comment by gasinvein** [comment] 2021-03-17 15:05
Let's keep this open for visibility until the issue is fixed on KDE runtime side.

**Comment by ilya-fedin** [comment] 2021-04-02 12:39
Looks like new KDE runtime version is released

**Closed by ilya-fedin** 2021-04-02 12:39 UTC
