### ISSUE TITLE
Telegram not running in background

### ISSUE THREAD

**Issue by daniel-wtd** [flathub/org.telegram.desktop#168] opened 2020-05-10 10:06 UTC
I thought in some previous versions, that telegram was running in background. Since some versions, this is no longer the case. When the application is closed, no more notifications come in and no background process is running.

Do I miss something?

**Comment by ilya-fedin** [comment] 2020-05-10 10:11
Check that you have any tray extension installed and permitted the background permission (Telegram will request it if you try to enable autostart in Telegram settings)

**Comment by daniel-wtd** [comment] 2020-05-10 10:16
So, it depends on a tray extension? Interesting.

Tested it and can confirm.

**Comment by ilya-fedin** [comment] 2020-05-10 10:18
> So, it depends on a tray extension?

Yes, there are no quit option anywhere rather then in tray menu, so that telegram is closing by close button

**Comment by ilya-fedin** [comment] 2020-08-30 11:39
Since there are no answer, I assume that the issue is resolved

**Closed by ilya-fedin** 2020-08-30 11:39 UTC

**Comment by daniel-wtd** [comment] 2020-08-31 11:23
Answer? ^^ there was no question, but the statement "works as intended", therefore I don't invested any time here.

**Comment by ilya-fedin** [comment] 2020-08-31 12:11
> Answer?

Yeah, I expected that you tell if something is wrong or close the issue yourself if it is resolved...

**Comment by daniel-wtd** [comment] 2020-08-31 12:14
Understood, will do so in the future :+1:
