### ISSUE TITLE
Graphics problem after update runtime  

### ISSUE THREAD

**Issue by cho2** [flathub/org.telegram.desktop#83] opened 2019-08-09 08:19 UTC
![Peek 2019-08-09 15-11](https://user-images.githubusercontent.com/6271071/62764757-d2821500-bab8-11e9-8b5d-ceb043b6aa7a.gif)

OS: openSUSE Leap 15.0

```
flatpak --version
Flatpak 1.2.3
```
```
flatpak info  org.telegram.desktop

Telegram Desktop - Telegram Desktop messenger

        ID: org.telegram.desktop
       Ref: app/org.telegram.desktop/x86_64/stable
Arsitektur: x86_64
    Cabang: stable
     Versi: 1.7.14
   Lisensi: GPL-3.0
      Asal: flathub
   Koleksi: org.flathub.Stable
Pemasangan: system
 Terpasang: 66,0 MB
   Runtime: org.kde.Platform/x86_64/5.12
       Sdk: org.kde.Sdk/x86_64/5.12

     Komit: 48c2595cdb8d15232f28afa1463a36480193554de55ae299c0a49bdb68a28bd5
     Induk: 4d56ddf2745d22b1123d5d58c8a54a21d6e20d31d3bf05fb864b7ead3e5e3b55
    Subjek: Drop temporary patch and use upstream solution instead (b422fcac)
   Tanggal: 2019-07-09 13:13:54 +0000
```

**Comment by grulja** [comment] 2019-08-09 09:32
Fixed with https://github.com/flathub/org.telegram.desktop/commit/be6087d536c42048f9e1ad45979b8323dc7023a1.

**Closed by grulja** 2019-08-09 09:32 UTC

**Comment by TingPing** [comment] 2019-08-09 22:15
@grulja 	If you force X you might as well just remove the Wayland permission?

**Comment by grulja** [comment] 2019-08-10 05:15
I want to investigate what is wrong and enable it again. I couldn't reproduce this on Plasma so it might be an issue in Mutter.
