### ISSUE TITLE
Running Telegram from GNOME shell opens a new instance every time

### ISSUE THREAD

**Issue by bertogg** [flathub/org.telegram.desktop#62] opened 2019-01-21 12:09 UTC
Running Telegram from the GNOME shell (or from the command line) no longer brings the current instance to the foreground but it opens a new one instead.

**Comment by bertogg** [comment] 2019-01-21 13:34
Using Debian stable here / GNOME 3.22.2

I can reproduce the problem reliably. If I revert to commit 9d758933f1b718c8a4c553daaa27eb4bc8afbec34698a6825a2f8efc16c06c73 ("Another build attempt (3f022521)") then it works fine.

Perhaps I need to log out and in again ? I'll try later (and I'll try to bisect to find the first release with this problem), I can't close the session now :)

**Comment by jurf** [comment] 2019-01-21 15:02
@grulja: can’t reproduce this. I mean, it has no reason not to work, it just a different subdirectory.

@bertogg: can you try opening a Telegram instance and seeingif you get something similar to this?:

```
❯ flatpak run --command=sh org.telegram.desktop
sh-4.4$ export |grep TMPDIR
export TMPDIR="/var/tmp"
sh-4.4$ ls $TMPDIR
a95e2b79b21efd77275eb8c588453a15
```

**Comment by bertogg** [comment] 2019-01-21 17:55
Ok, this is odd. TMPDIR is not set in the sandbox.

But I see TMPDIR=/var/tmp in the metadata file. What's more, if I manually add FOO=bar to the Environment section, then FOO is set in the sandbox, but still no TMPDIR.

I'm using Flatpak 1.0.6.

**Comment by bertogg** [comment] 2019-01-21 18:02
I see that Flatpak doesn't let you override TMPDIR:

https://github.com/flatpak/flatpak/commit/6711b56794294a9627696ff08a3f2c4ecdeb164a

**Comment by nexfwall** [comment] 2019-01-27 10:47
Can't reproduce in Fedora 29 Silverblue.
When closing Telegram Desktop, it's closing main window and runs in background. Opening it again brings the main window up.
Or, maybe it's fixed already.

**Comment by bertogg** [comment] 2019-01-27 11:48
Can you try to see if TMPDIR is set inside the sandbox?

```
$ flatpak --version
Flatpak 1.0.6
$ flatpak run --env=TMPDIR=/var/tmp --command=sh org.telegram.desktop
sh-4.4$ echo $TMPDIR

sh-4.4$ 
```

**Comment by nexfwall** [comment] 2019-01-27 13:00
And even if I delete the override from cmdline:

```
[ezakharov@E101-Y52015IKBA ~]$ flatpak run --command=sh org.telegram.desktop
sh-4.4$ echo $TMPDIR
/var/tmp
sh-4.4$ 
```

**Comment by bertogg** [comment] 2019-01-28 12:22
I just discussed this with Alex Larsson. This seems to be a bug in Flatpak (it should be possible to override TMPDIR) but it's unclear why this is happening.

Since the Flatpak versions in (at least) Debian stable and testing are affected, he suggests going back to the wrapper script for the case of Telegram.

I filed a bug against Flatpak (see reference above).

**Comment by grulja** [comment] 2019-01-28 13:21
The change has been reverted.

**Closed by grulja** 2019-01-28 13:21 UTC
